// <auto-generated />
using System;
using CivilRegistryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CivilRegistryAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625193952_migrv2")]
    partial class migrv2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CivilRegistryAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.BranchHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchHolidays");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.BranchSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("MaxAppointmentsPerSlot")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("PeakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("PeakStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchSchedules");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CenterLatitude = 30.0626,
                            CenterLongitude = 31.249700000000001,
                            Name = "القاهرة"
                        },
                        new
                        {
                            Id = 2,
                            CenterLatitude = 30.013100000000001,
                            CenterLongitude = 31.2089,
                            Name = "الجيزة"
                        },
                        new
                        {
                            Id = 3,
                            CenterLatitude = 31.200099999999999,
                            CenterLongitude = 29.918700000000001,
                            Name = "الإسكندرية"
                        },
                        new
                        {
                            Id = 4,
                            CenterLatitude = 30.7226,
                            CenterLongitude = 31.723099999999999,
                            Name = "الشرقية"
                        },
                        new
                        {
                            Id = 5,
                            CenterLatitude = 31.040900000000001,
                            CenterLongitude = 31.381900000000002,
                            Name = "الدقهلية"
                        },
                        new
                        {
                            Id = 6,
                            CenterLatitude = 30.847999999999999,
                            CenterLongitude = 30.343599999999999,
                            Name = "البحيرة"
                        },
                        new
                        {
                            Id = 7,
                            CenterLatitude = 30.596499999999999,
                            CenterLongitude = 30.9876,
                            Name = "المنوفية"
                        },
                        new
                        {
                            Id = 8,
                            CenterLatitude = 30.3292,
                            CenterLongitude = 31.216799999999999,
                            Name = "القليوبية"
                        },
                        new
                        {
                            Id = 9,
                            CenterLatitude = 30.875299999999999,
                            CenterLongitude = 31.0364,
                            Name = "الغربية"
                        },
                        new
                        {
                            Id = 10,
                            CenterLatitude = 31.110700000000001,
                            CenterLongitude = 30.938800000000001,
                            Name = "كفر الشيخ"
                        },
                        new
                        {
                            Id = 11,
                            CenterLatitude = 29.308399999999999,
                            CenterLongitude = 30.8428,
                            Name = "الفيوم"
                        },
                        new
                        {
                            Id = 12,
                            CenterLatitude = 29.066099999999999,
                            CenterLongitude = 31.099399999999999,
                            Name = "بني سويف"
                        },
                        new
                        {
                            Id = 13,
                            CenterLatitude = 28.0871,
                            CenterLongitude = 30.761800000000001,
                            Name = "المنيا"
                        },
                        new
                        {
                            Id = 14,
                            CenterLatitude = 27.180900000000001,
                            CenterLongitude = 31.183700000000002,
                            Name = "أسيوط"
                        },
                        new
                        {
                            Id = 15,
                            CenterLatitude = 26.556899999999999,
                            CenterLongitude = 31.694800000000001,
                            Name = "سوهاج"
                        },
                        new
                        {
                            Id = 16,
                            CenterLatitude = 26.155100000000001,
                            CenterLongitude = 32.716000000000001,
                            Name = "قنا"
                        },
                        new
                        {
                            Id = 17,
                            CenterLatitude = 25.687200000000001,
                            CenterLongitude = 32.639600000000002,
                            Name = "الأقصر"
                        },
                        new
                        {
                            Id = 18,
                            CenterLatitude = 24.088899999999999,
                            CenterLongitude = 32.899799999999999,
                            Name = "أسوان"
                        },
                        new
                        {
                            Id = 19,
                            CenterLatitude = 24.682600000000001,
                            CenterLongitude = 34.153100000000002,
                            Name = "البحر الأحمر"
                        },
                        new
                        {
                            Id = 20,
                            CenterLatitude = 25.488900000000001,
                            CenterLongitude = 29.0,
                            Name = "الوادي الجديد"
                        },
                        new
                        {
                            Id = 21,
                            CenterLatitude = 31.354299999999999,
                            CenterLongitude = 27.237300000000001,
                            Name = "مطروح"
                        },
                        new
                        {
                            Id = 22,
                            CenterLatitude = 30.284099999999999,
                            CenterLongitude = 33.625900000000001,
                            Name = "شمال سيناء"
                        },
                        new
                        {
                            Id = 23,
                            CenterLatitude = 28.538799999999998,
                            CenterLongitude = 33.998100000000001,
                            Name = "جنوب سيناء"
                        },
                        new
                        {
                            Id = 24,
                            CenterLatitude = 31.256499999999999,
                            CenterLongitude = 32.284100000000002,
                            Name = "بورسعيد"
                        },
                        new
                        {
                            Id = 25,
                            CenterLatitude = 30.596499999999999,
                            CenterLongitude = 32.271500000000003,
                            Name = "الإسماعيلية"
                        },
                        new
                        {
                            Id = 26,
                            CenterLatitude = 29.966799999999999,
                            CenterLongitude = 32.549799999999998,
                            Name = "السويس"
                        },
                        new
                        {
                            Id = 27,
                            CenterLatitude = 31.416499999999999,
                            CenterLongitude = 31.813300000000002,
                            Name = "دمياط"
                        });
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredDocuments")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "استخراج أو تجديد بطاقة الرقم القومي",
                            DurationMinutes = 30,
                            Name = "بطاقة الرقم القومي",
                            RequiredDocuments = "بطاقة الرقم القومي منتهية الصلاحية\nصورة شخصية حديثة\nشهادة الميلاد"
                        },
                        new
                        {
                            Id = 2,
                            Description = "استخراج شهادة ميلاد",
                            DurationMinutes = 20,
                            Name = "شهادة الميلاد",
                            RequiredDocuments = "بطاقة الرقم القومي للأب أو الأم\nعقد الزواج\nشهادة الميلاد الأصلية من المستشفى"
                        },
                        new
                        {
                            Id = 3,
                            Description = "توثيق عقد الزواج",
                            DurationMinutes = 45,
                            Name = "عقد الزواج",
                            RequiredDocuments = "بطاقة الرقم القومي للطرفين\nشهادة ميلاد الطرفين\nموافقة ولي الأمر لو العروسة أقل من 21 سنة"
                        },
                        new
                        {
                            Id = 4,
                            Description = "استخراج شهادة وفاة",
                            DurationMinutes = 20,
                            Name = "شهادة الوفاة",
                            RequiredDocuments = "بطاقة الرقم القومي للمتوفي\nتقرير الوفاة من المستشفى أو الطبيب\nبطاقة الرقم القومي لمقدم الطلب"
                        },
                        new
                        {
                            Id = 5,
                            Description = "استخراج قيد الأسرة",
                            DurationMinutes = 15,
                            Name = "قيد الأسرة",
                            RequiredDocuments = "بطاقة الرقم القومي\nعقد الزواج"
                        });
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.ServiceUnavailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ServiceUnavailabilities");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.ApplicationUser", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("CivilRegistryAPI.Models.Governorate", "Governorate")
                        .WithMany("Users")
                        .HasForeignKey("GovernorateId");

                    b.Navigation("Branch");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Appointment", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.Branch", "Branch")
                        .WithMany("Appointments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivilRegistryAPI.Models.ServiceType", "ServiceType")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivilRegistryAPI.Models.ApplicationUser", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ServiceType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Branch", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.Governorate", "Governorate")
                        .WithMany("Branches")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.BranchHoliday", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.Branch", "Branch")
                        .WithMany("Holidays")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.BranchSchedule", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.Branch", "Branch")
                        .WithMany("Schedules")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Complaint", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("CivilRegistryAPI.Models.ApplicationUser", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Rating", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.Appointment", "Appointment")
                        .WithOne("Rating")
                        .HasForeignKey("CivilRegistryAPI.Models.Rating", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivilRegistryAPI.Models.Branch", "Branch")
                        .WithMany("Ratings")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivilRegistryAPI.Models.ApplicationUser", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.ServiceUnavailability", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.Branch", "Branch")
                        .WithMany("ServiceUnavailabilities")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivilRegistryAPI.Models.ServiceType", "ServiceType")
                        .WithMany("ServiceUnavailabilities")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivilRegistryAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CivilRegistryAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Complaints");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Appointment", b =>
                {
                    b.Navigation("Rating");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Branch", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Holidays");

                    b.Navigation("Ratings");

                    b.Navigation("Schedules");

                    b.Navigation("ServiceUnavailabilities");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.Governorate", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CivilRegistryAPI.Models.ServiceType", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceUnavailabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
