// <auto-generated />
using System;
using Mawidy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mawidy.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mawidy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNotified")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeSlot")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WantsReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("WantsSms")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("QueueCount")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WaitTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("GovernorateId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.BranchHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchHolidays");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.BranchSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("MaxAppointmentsPerSlot")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("PeakEndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("PeakStartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("BranchSchedules");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.CaseTimelineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LegalCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LegalCaseId");

                    b.ToTable("CaseTimelineEvents");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("UserId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TotalRooms")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.CourtDepartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.ToTable("CourtDepartments");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.CourtService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EstimatedTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredDocumentsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CourtServices");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Governorate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CenterLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CenterLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CenterLatitude = 30.0626,
                            CenterLongitude = 31.249700000000001,
                            Emoji = "",
                            Name = "القاهرة",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            CenterLatitude = 30.013100000000001,
                            CenterLongitude = 31.2089,
                            Emoji = "",
                            Name = "الجيزة",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 3,
                            CenterLatitude = 31.200099999999999,
                            CenterLongitude = 29.918700000000001,
                            Emoji = "",
                            Name = "الإسكندرية",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 4,
                            CenterLatitude = 30.7226,
                            CenterLongitude = 31.723099999999999,
                            Emoji = "",
                            Name = "الشرقية",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 5,
                            CenterLatitude = 31.040900000000001,
                            CenterLongitude = 31.381900000000002,
                            Emoji = "",
                            Name = "الدقهلية",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 6,
                            CenterLatitude = 30.847999999999999,
                            CenterLongitude = 30.343599999999999,
                            Emoji = "",
                            Name = "البحيرة",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 7,
                            CenterLatitude = 30.596499999999999,
                            CenterLongitude = 30.9876,
                            Emoji = "",
                            Name = "المنوفية",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 8,
                            CenterLatitude = 30.3292,
                            CenterLongitude = 31.216799999999999,
                            Emoji = "",
                            Name = "القليوبية",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 9,
                            CenterLatitude = 30.875299999999999,
                            CenterLongitude = 31.0364,
                            Emoji = "",
                            Name = "الغربية",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 10,
                            CenterLatitude = 31.110700000000001,
                            CenterLongitude = 30.938800000000001,
                            Emoji = "",
                            Name = "كفر الشيخ",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 11,
                            CenterLatitude = 29.308399999999999,
                            CenterLongitude = 30.8428,
                            Emoji = "",
                            Name = "الفيوم",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 12,
                            CenterLatitude = 29.066099999999999,
                            CenterLongitude = 31.099399999999999,
                            Emoji = "",
                            Name = "بني سويف",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 13,
                            CenterLatitude = 28.0871,
                            CenterLongitude = 30.761800000000001,
                            Emoji = "",
                            Name = "المنيا",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 14,
                            CenterLatitude = 27.180900000000001,
                            CenterLongitude = 31.183700000000002,
                            Emoji = "",
                            Name = "أسيوط",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 15,
                            CenterLatitude = 26.556899999999999,
                            CenterLongitude = 31.694800000000001,
                            Emoji = "",
                            Name = "سوهاج",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 16,
                            CenterLatitude = 26.155100000000001,
                            CenterLongitude = 32.716000000000001,
                            Emoji = "",
                            Name = "قنا",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 17,
                            CenterLatitude = 25.687200000000001,
                            CenterLongitude = 32.639600000000002,
                            Emoji = "",
                            Name = "الأقصر",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 18,
                            CenterLatitude = 24.088899999999999,
                            CenterLongitude = 32.899799999999999,
                            Emoji = "",
                            Name = "أسوان",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 19,
                            CenterLatitude = 24.682600000000001,
                            CenterLongitude = 34.153100000000002,
                            Emoji = "",
                            Name = "البحر الأحمر",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 20,
                            CenterLatitude = 25.488900000000001,
                            CenterLongitude = 29.0,
                            Emoji = "",
                            Name = "الوادي الجديد",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 21,
                            CenterLatitude = 31.354299999999999,
                            CenterLongitude = 27.237300000000001,
                            Emoji = "",
                            Name = "مطروح",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 22,
                            CenterLatitude = 30.284099999999999,
                            CenterLongitude = 33.625900000000001,
                            Emoji = "",
                            Name = "شمال سيناء",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 23,
                            CenterLatitude = 28.538799999999998,
                            CenterLongitude = 33.998100000000001,
                            Emoji = "",
                            Name = "جنوب سيناء",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 24,
                            CenterLatitude = 31.256499999999999,
                            CenterLongitude = 32.284100000000002,
                            Emoji = "",
                            Name = "بورسعيد",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 25,
                            CenterLatitude = 30.596499999999999,
                            CenterLongitude = 32.271500000000003,
                            Emoji = "",
                            Name = "الإسماعيلية",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 26,
                            CenterLatitude = 29.966799999999999,
                            CenterLongitude = 32.549799999999998,
                            Emoji = "",
                            Name = "السويس",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 27,
                            CenterLatitude = 31.416499999999999,
                            CenterLongitude = 31.813300000000002,
                            Emoji = "",
                            Name = "دمياط",
                            NameAr = "",
                            NameEn = "",
                            Region = "",
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.LegalCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Defendant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Plaintiff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("LegalCases");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operators", (string)null);
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.OperatorService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstimatedTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("OperatorServices", (string)null);
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.QueueTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EstimatedWaitTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TicketNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasFilter("[BookingId] IS NOT NULL");

                    b.HasIndex("CourtId");

                    b.ToTable("QueueTickets");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.ServiceDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocType")
                        .HasColumnType("int");

                    b.Property<string>("NoteAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TextAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceDocuments", (string)null);
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredDocuments")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "الحصول على بطاقة الرقم القومي لأول مرة أو تجديدها",
                            DurationMinutes = 30,
                            Name = "إصدار بطاقة الرقم القومي",
                            RequiredDocuments = "استمارة الحصول على بطاقة الرقم القومي\nمستند إثبات الشخصية الحالي\nمستند إثبات محل الإقامة"
                        },
                        new
                        {
                            Id = 2,
                            Description = "الحصول على شهادة ميلاد مميكنة",
                            DurationMinutes = 20,
                            Name = "إصدار شهادة الميلاد",
                            RequiredDocuments = "صورة بطاقة الرقم القومي للأب أو الأم\nطلب إصدار شهادة الميلاد"
                        },
                        new
                        {
                            Id = 3,
                            Description = "توثيق الزواج وإصدار الوثيقة",
                            DurationMinutes = 45,
                            Name = "وثيقة الزواج",
                            RequiredDocuments = "صورة بطاقة الرقم القومي للزوج والزوجة\nالشهادة الصحية"
                        },
                        new
                        {
                            Id = 4,
                            Description = "توثيق الطلاق وإصدار الوثيقة",
                            DurationMinutes = 20,
                            Name = "وثيقة الطلاق",
                            RequiredDocuments = "صورة بطاقة الرقم القومي للطرفين\nحكم المحكمة أو إقرار الطلاق"
                        },
                        new
                        {
                            Id = 5,
                            Description = "إصدار قيد عائلي مميكن",
                            DurationMinutes = 15,
                            Name = "قيد عائلي",
                            RequiredDocuments = "صور بطاقات الرقم القومي لأفراد الأسرة\nشهادات الميلاد المميكنة للأولاد"
                        });
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.ServiceUnavailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("ServiceUnavailabilities");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.VirtualQueueEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ServiceKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("VirtualQueueEntries", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.HasOne("Mawidy.Domain.Entities.Governorate", "Governorate")
                        .WithMany("Users")
                        .HasForeignKey("GovernorateId");

                    b.Navigation("Branch");

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Branch", "Branch")
                        .WithMany("Appointments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ServiceType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Court", "Court")
                        .WithMany("Bookings")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.CourtDepartment", "Department")
                        .WithMany("Bookings")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.CourtService", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Department");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Branch", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.District", "District")
                        .WithMany("Branches")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.Governorate", "Governorate")
                        .WithMany("Branches")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.Operator", "Operator")
                        .WithMany("Branches")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Governorate");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.BranchHoliday", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Branch", "Branch")
                        .WithMany("Holidays")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.BranchSchedule", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Branch", "Branch")
                        .WithMany("Schedules")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.CaseTimelineEvent", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.LegalCase", "LegalCase")
                        .WithMany("TimelineEvents")
                        .HasForeignKey("LegalCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegalCase");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Complaint", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("Mawidy.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.CourtDepartment", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Court", "Court")
                        .WithMany("Departments")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.District", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Governorate", "Governorate")
                        .WithMany("Districts")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.LegalCase", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Court", "Court")
                        .WithMany("LegalCases")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.CourtDepartment", "Department")
                        .WithMany("LegalCases")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.OperatorService", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Operator", "Operator")
                        .WithMany("Services")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.QueueTicket", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Booking", "Booking")
                        .WithOne("QueueTicket")
                        .HasForeignKey("Mawidy.Domain.Entities.QueueTicket", "BookingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Mawidy.Domain.Entities.Court", "Court")
                        .WithMany("QueueTickets")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Court");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Rating", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Appointment", "Appointment")
                        .WithOne("Rating")
                        .HasForeignKey("Mawidy.Domain.Entities.Rating", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.Branch", "Branch")
                        .WithMany("Ratings")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.ServiceUnavailability", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Branch", "Branch")
                        .WithMany("ServiceUnavailabilities")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("ServiceUnavailabilities")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.VirtualQueueEntry", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.Branch", "Branch")
                        .WithMany("QueueEntries")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mawidy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Mawidy.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Complaints");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Booking", b =>
                {
                    b.Navigation("QueueTicket");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Holidays");

                    b.Navigation("QueueEntries");

                    b.Navigation("Ratings");

                    b.Navigation("Schedules");

                    b.Navigation("ServiceUnavailabilities");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Court", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Departments");

                    b.Navigation("LegalCases");

                    b.Navigation("QueueTickets");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.CourtDepartment", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LegalCases");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.CourtService", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.District", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Governorate", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Districts");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.LegalCase", b =>
                {
                    b.Navigation("TimelineEvents");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.Operator", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Mawidy.Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceUnavailabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
